%% CONFIG
% Specify the directory where your data lives
BIDS_DIR = '/Users/fmri/proj/SSH/BIDS_dataset';
SCAN_DIR = fullfile(BIDS_DIR, 'derivatives', 'fmriprep-fmap');

% Specify the list of subjects you want to process
% Loop through subjects, runs
SUBJECTS = {
    'sub-SD',...
    'sub-KP',...
    'sub-003',...
    'sub-020',...
    'sub-035',...
    'sub-039',...
    'sub-040',...
    'sub-043',...
    'sub-048',...
    'sub-053',...
    'sub-055',...
    'sub-057',...
    'sub-058',...
    'sub-059',...
    'sub-081',...
    'sub-096',...
    'sub-098',...
    'sub-103',...
    'sub-108',...
    'sub-110',...
    'sub-111',...
    'sub-122',...
    'sub-155',...
};
task_var = 'nochmani';


UNZIP_GZ = true; % Unzip nii.gz files to .nii? (Run this if it hasn't been done yet for the subject's fmriprep data)

%% Set up and run batch
% this loop will perform preprocessing steps for all subjects specified in
% the list "subjects"
for i = 1:numel(SUBJECTS)
    disp(['Smoothing data for ', SUBJECTS{i}, '...']); 
    
    % specify directory with functional data
    func_dir = fullfile(SCAN_DIR, SUBJECTS{i}, 'func'); 

    % Unzip functional data
    if UNZIP_GZ == true
        list = dir(fullfile(func_dir, 'sub-*task-*space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii.gz'));
        func_to_unzip = fullfile({list.folder}, {list.name})';
        gunzip(func_to_unzip);
    end

    % Find and select the functional data
    func = spm_select('ExtFPList', func_dir, '^sub-*.*task-*.*space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii$');
    
    % Set up batch
    smooth_data = cellstr(func);
    matlabbatch{1}.spm.spatial.smooth.data = smooth_data;
    matlabbatch{1}.spm.spatial.smooth.fwhm = [8 8 8];
    matlabbatch{1}.spm.spatial.smooth.dtype = 0;
    matlabbatch{1}.spm.spatial.smooth.im = 0;
    matlabbatch{1}.spm.spatial.smooth.prefix = 'smoothed_';

    spm_jobman('run',matlabbatch) 
    clear matlabbatch % clear matlabbatch
end

